### ISSUE TITLE
Husky hardware

### ISSUE THREAD

**Issue by Russ76** [MobileRobotics-Ulaval/husky-trainer#2]
This code may be perfect for a project we are working on but we do not have a Clearpath Husky. Wouldn't the nodes work with similar hardware? What is required in the platform? Maybe there's a project or link you could point me to? Thanks!

**Comment by davidlandry93** [comment]
Hi Russ,

Since I ported it to ROS Indigo there are no hard dependencies to the Husky code. All the topics used are generic ROS messages like Twist or Pose.

So I guess the big conditions on you hardware would be 1) differential steering and 2) lidar sensor. Since I never tested it on anything else than our Husky there might (will) be some hiccups, but i'll be glad to help if needed.

A useful resource would be the paper I used as inspiration,which you can read [here](http://ais.informatik.uni-freiburg.de/publications/papers/sprunk13iros.pdf).

Good luck!

**Comment by Russ76** [comment]
Thanks for the answer. My bot does have differential steering and stereo vision and no lidar but I don't think that will be an issue. The ZED camera depth data is interpreted as lidar data, I believe.
Thanks for the link to the paper!
(Um, you may want to update your PC...)
:)
